import Head from 'next/head'
import { HomePageComponent } from '@/components/home/HomePageComponent'
import { HomePageLayout } from '@/components/UI/HomePageLayout'
import { useRouter } from 'next/router'
import { useEffect } from 'react';


export default function Home() {

  const router = useRouter();

  return (
    <>
      <Head>
        <title>HouseKeeper | דף הבית</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePageLayout name="לירון">
          <HomePageComponent />
        </HomePageLayout>
      </main>
    </>
  )
}
