import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  async function getData(){
    const apiEndPoint = "http://localhost:3000/api/getData";
    const response = await fetch(apiEndPoint);
    const resJson = await response.json();
    console.log(resJson);
  };

  useEffect(()=>{
    getData();
  },[]);

  return (
    <>
      <Head>
        <title>HouseKeeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>House Kepper Application</h1>
      </main>
    </>
  )
}
