import Head from 'next/head';
import Image from 'next/image'
import { useRouter } from 'next/router';
import React, { useState } from 'react'
import style from "../styles/Login.module.css"
import { CustomInput } from '@/components/UI/FormFields/CustomInput';
import Link from 'next/link';

export default function RegisterPage() {
    const router = useRouter();

    // Form Fields
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");

    // Handle submit login function
    const handleRegisterSubmit = async (event: any) => {
        event.preventDefault();
        const data = {
            email,
            password,
        }

        console.log(data);
        // router.replace("/home");

        // Add after finish backned: 
        // const url = "https://localhost:3000/api/login";
        // const response = await fetch(url, {
        //     method: "POST",
        //     mode: "cors",
        //     headers: {
        //         "Content-Type": "application/json"
        //     },
        //     body: JSON.stringify(data)
        // });
        // console.log("response: ", response);
    }

    return (
        <>
            <Head>
                <title>HouseKeeper | הרשמה</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${style.login_main} ${style.register}`} dir='rtl'>
                <div className={style.login_logo}>
                    <Image src="/housekeeper.jpg" fill alt="House Keeper" />
                </div>
                <div className={style.login_form}>
                    <h1 className={`blue_title ${style.form_title}`}>הרשמה</h1>
                    <form dir='rtl' onSubmit={(e) => handleRegisterSubmit(e)}>
                        <div className={style.field_container}>
                            <CustomInput value={email} onChange={(e) => setEmail(e.target.value)} required label="שם מלא" dir='ltr' type='text' />
                            <CustomInput value={email} onChange={(e) => setEmail(e.target.value)} required label="כתובת אימייל" dir='ltr' type='text' />
                            <CustomInput value={password} onChange={(e) => setPassword(e.target.value)} required label="סיסמה" dir='ltr' type='password' />
                            <CustomInput value={email} onChange={(e) => setEmail(e.target.value)} required label="אישור סיסמה" dir='ltr' type='text' />
                        </div>
                        <button className={style.submit_btn} type='submit'>להרשמה</button>
                    </form>
                </div>
            </main>
        </>
    )
}
